sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t vineetcodes/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true vineetcodes/docker-react npm run test
